### PR TITLE
Add support for jquery event binding

### PR DESCRIPTION
**Pull request by vernard**
Proposed solution in issue #37.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
LGTM (Looks good to me)
@paales Does this PR LGTM to you too?

**Comment by paales** [comment]
I don't get why this is necessary. I've never needed the extensive checks to make something working with the prototype+jquery. Maybe I'm not understanding the issue..

**Comment by vernard** [comment]
I tested your extension on magento 1.9.0.1 (without this fix) and it was working fine.
The issue can be replicated by using magento 1.4.2. This might be a prototype issue on older versions.

So, this fix allows markdown plugin to work on magento older version such as 1.4.2.

**Comment by SchumacherFM** [comment]
I'm not interested in supporting old and insecure Magento versions.

**Pull request closed without merging**
